// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto.infra.Data;

#nullable disable

namespace projeto.infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230825182012_AdicionadoCollation")]
    partial class AdicionadoCollation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_LATIN1_GENERAL_CP1_CI_AI")
                .HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("projeto.domain.Entity.ProdutosDisponiveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProdutosEmEstoque");
                });

            modelBuilder.Entity("projeto.domain.Entity.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoUtilizadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeUtilizado")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoUtilizadoId");

                    b.HasIndex(new[] { "Status", "Nome" }, "X-Consultas-Indexes");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("projeto.domain.Entity.Projeto", b =>
                {
                    b.HasOne("projeto.domain.Entity.ProdutosDisponiveis", "ProdutoUtilizado")
                        .WithMany("Projetos")
                        .HasForeignKey("ProdutoUtilizadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProdutoUtilizado");
                });

            modelBuilder.Entity("projeto.domain.Entity.ProdutosDisponiveis", b =>
                {
                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
