# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./projeto.service.tests
  
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./projeto.service.tests
  
    - name: Build API 
      run: dotnet build --no-restore
      working-directory: ./projeto.service

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx  
      uses: docker/setup-buildx-action@v2
    
    - name: Build image 
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/estoque:v0.1
      working-directory: ./estoque.service
    
    - name: Pushing image on docker hub 
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/estoque:v0.1
    
    - name: Deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd icarus.estoque && docker stop container-estoque && docker rm container-estoque && docker rmi k4im/estoque:v0.1 && docker-compose up -d 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOSTNAME }}
        port: ${{ secrets.PORT }}
        privateKey: ${{ secrets.PRIVATE_KEY}}
